# Generated by Django 5.1 on 2024-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default='Field for information about lesson'),
        ),
    ]
